### ISSUE TITLE
Memory Issues

### ISSUE THREAD

**Issue by Jordan-Anjie-Lu** [scorzy/IdleSpace2#2]
This particular issue looks like a memory leak. When you change between tabs (which ones are currently unknown, I'll probably run a few tests in a bit), more space is taken up by the array and object. This results in the following. (This was on my first prestige, so there's still a lot of interaction.)

**Initial load (or close to it):**
![2020-08-12 15_41_37-Window](https://user-images.githubusercontent.com/49064210/89979166-77c65f00-dcb2-11ea-919a-f2b9090bd941.png)

**7 minutes later:**
![2020-08-12 15_41_54-Window](https://user-images.githubusercontent.com/49064210/89979170-78f78c00-dcb2-11ea-8150-7c63554f3e60.png)

**10 minutes later:**
![2020-08-12 15_41_59-Window](https://user-images.githubusercontent.com/49064210/89979172-78f78c00-dcb2-11ea-95c1-01f07ca4abb7.png)

**7 minutes later. At this point, I set it to idle without any user interaction.**
![2020-08-12 15_42_02-Window](https://user-images.githubusercontent.com/49064210/89979174-79902280-dcb2-11ea-97ab-38c5f003b8b7.png)

**10 minutes later. Note that it hasn't used additional memory (It lists it as having shrunk, but that looks to be the scripts having shrunk? Optimization or something?) At this point, I resume messing around with the different tabs.**
![2020-08-12 15_42_06-Window](https://user-images.githubusercontent.com/49064210/89979176-7a28b900-dcb2-11ea-83aa-115b22530dc9.png)

**12 minutes later.**
![2020-08-12 15_42_10-Window](https://user-images.githubusercontent.com/49064210/89979177-7ac14f80-dcb2-11ea-91e5-27e90a858ede.png)

This does eventually lead to slowdown of the browser, and perhaps other unwanted side-effects. This can be cleared by refreshing the page.

All snapshots used, and a ZIP file of the snapshots: https://drive.google.com/drive/folders/1As8D_MqfSBCo_csiIx0aI3TGNPiodPeb?usp=sharing

Browser Info: 79.0 Firefox (stable)
Windows 10 version 2004

**Comment by Jordan-Anjie-Lu** [comment]
Current savegame: 
[IdleSpace2.txt](https://github.com/scorzy/IdleSpace2/files/5060844/IdleSpace2.txt)

**Comment by scorzy** [comment]
I looked for missing unsubscriptions, removed some animations, and disabled Ivy but the problem is not solved.

Unfortunately Angular has some memory leaks:
https://github.com/angular/angular/issues?q=is%3Aopen+is%3Aissue+label%3A%22severity4%3A+memleak%22

I hope Angular team fixes it because it's hard to tell if it's my code fault or Angular fault.
