### ISSUE TITLE
upgrade Higher Module Level issue

### ISSUE THREAD

**Issue by shfxxer** [scorzy/IdleSpace2#22]
too many HML upgrade would cause auto upgrade design become invalid actually.

my max level is 3.98e4,auto upgrade rate set to 1 the module level is 3.65e4

that means price of the ship is 6.7e 506,about 5e435 years 

should auto upgrade  design option limits the max build time?

**Comment by scorzy** [comment]
It should, however it doesn't decrease the module level. I'll add an option to allow downgrade.
